- hosts: host
  become: yes
  vars:
    SERVER_IP: "{{ groups.server[0] }}"
    RANCHER_SERVER_URL: "{{ SERVER_IP }}"
    RANCHER_ADMIN_PASSWORD: "admin"
    CLUSTER_NAME: "cluster001"
    ROLEFLAGS: "--etcd --controlplane --worker"
  tasks:

    - name: "Make Login Racher Server"
      uri:
        url: https://{{ SERVER_IP }}/v3-public/localProviders/local?action=login
        method: POST
        validate_certs: False
        body_format: json
        body: {"username":"admin", "password":"admin"}
        headers:
          Content-Type: "application/json"
        status_code: 201
      register: login
      until: login.status == 201
      retries: 3
      delay: 10
      failed_when: login.status not in [201]

    - name: "Update Rancher Server Password"
      uri:
        url: https://{{ SERVER_IP }}/v3/users?action=changepassword
        method: POST
        validate_certs: False
        body_format: json
        body: '{"currentPassword":"admin", "newPassword":"{{ RANCHER_ADMIN_PASSWORD }}"}'
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ login.json.token }}"
        status_code: 200
      when: login.status in [201]
    
    - name: "Create Api Key"
      uri:
        url: https://{{ SERVER_IP }}/v3/token
        method: POST
        validate_certs: False
        body_format: json
        body: {"type":"token","description":"automation"}
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ login.json.token }}"
        status_code: 201
      register: api_key

    - name: "Set Rancher Server Url"
      uri:
        url: https://{{ SERVER_IP }}/v3/settings/server-url
        method: PUT
        validate_certs: False
        body_format: json
        body: '{"name":"server-url","value":"https://{{ RANCHER_SERVER_URL }}"}'
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ api_key.json.token }}"
        status_code: 200
    
    - name: "Create Custom Cluster"
      uri:
        url: https://{{ SERVER_IP }}/v3/cluster
        method: POST
        validate_certs: False
        body_format: json
        body: '{"dockerRootDir":"/var/lib/docker","enableNetworkPolicy":false,"type":"cluster","rancherKubernetesEngineConfig":{"addonJobTimeout":30,"ignoreDockerVersion":true,"sshAgentAuth":false,"type":"rancherKubernetesEngineConfig","authentication":{"type":"authnConfig","strategy":"x509"},"network":{"type":"networkConfig","plugin":"canal"},"ingress":{"type":"ingressConfig","provider":"nginx"},"monitoring":{"type":"monitoringConfig","provider":"metrics-server"},"services":{"type":"rkeConfigServices","kubeApi":{"podSecurityPolicy":false,"type":"kubeAPIService"},"etcd":{"snapshot":false,"type":"etcdService","extraArgs":{"heartbeat-interval":500,"election-timeout":5000}}}},"name":"{{ CLUSTER_NAME }}"}'
        status_code: 201
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ api_key.json.token }}"
      register: cluster
    
    - name: "Create Cluster Registration Token"
      uri:
        url: https://{{ SERVER_IP }}/v3/clusterregistrationtoken
        method: POST
        validate_certs: False
        body_format: json
        body: '{"type":"clusterRegistrationToken","clusterId":"{{ cluster.json.id }}"}'
        status_code: 201
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ api_key.json.token }}"
      register: node_command
    
    # - name: "Get Command To Start The Nodes"
    #   uri:
    #     url: https://{{ SERVER_IP }}/v3/clusterregistrationtoken?id="{{ cluster.json.id }}"
    #     method: GET
    #     validate_certs: no
    #     body_format: json
    #     status_code: 200
    #     headers:
    #       Content-Type: "application/json"
    #       Authorization: "Bearer {{ api_key.json.token }}"
    #   register: node_command
    
    - name: "Launch Command On Node"
      shell: '{{ node_command.json.nodeCommand[5:] }} {{ ROLEFLAGS }}'

    # - name: "Debug"
    #   debug:
    #     msg:
    #     - "{{ node_command.json.nodeCommand }} {{ ROLEFLAGS }}"