- hosts: rancher
  become: yes
  tasks:
    - name: "Install Docker Dependencies"
      yum:
        name: "{{ item.name }}"
        state: latest
      with_items:
        - { name: lvm2 }
        - { name: yum-utils }
        - { name: device-mapper }
        - { name: device-mapper-libs }
        - { name: device-mapper-event }
        - { name: device-mapper-event-libs }
        - { name: device-mapper-persistent-data }
    
    - name: "Add Docker Repository"
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: 0700   
    
    - name: "Install Docker"
      yum:
        name: "{{ item.name }}"
        state: latest
      with_items:
        - { name: docker-ce }
    
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes