- hosts: server
  become: yes
  tasks:

    - name: "Intall Rancher 2.2.6"
      command: docker run -d --restart=unless-stopped \
                 -p 80:80 -p 443:443 \
                 rancher/rancher:v2.2.6
    
    - name: "Waiting Server Being Up"
      uri:
        url: https://{{ groups.server[0] }}
        method: GET
        validate_certs: no
        status_code: 200
      register: result
      until: result.status == 200
      retries: 10
      delay: 6
      